.TH "_DIR" 3 "Fri Jan 15 2016" "Version By : V. Fontaine, M.Y. Megrini, N. Scotto Di Perto" "The Tiny Toy File System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_DIR \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "uint32_t \fBb_offset\fP"
.br
.ti -1c
.RI "uint32_t \fBb_size\fP"
.br
.ti -1c
.RI "struct \fBdirent\fP \fBbuf\fP [32]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file tfs\&.c\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t b_offset"

.PP
Definition at line 36 of file tfs\&.c\&.
.SS "uint32_t b_size"

.PP
Definition at line 37 of file tfs\&.c\&.
.SS "struct \fBdirent\fP buf[32]"

.PP
Definition at line 38 of file tfs\&.c\&.
.SS "int fd"

.PP
Definition at line 35 of file tfs\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for The Tiny Toy File System from the source code\&.
