.TH "_index" 3 "Fri Jan 15 2016" "Version By : V. Fontaine, M.Y. Megrini, N. Scotto Di Perto" "The Tiny Toy File System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_index \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int32_t \fBdirect\fP"
.br
.ti -1c
.RI "int32_t \fBindirect1\fP"
.br
.ti -1c
.RI "int32_t \fBindirect2\fP"
.br
.ti -1c
.RI "uint32_t \fBindirect1_addr\fP"
.br
.ti -1c
.RI "uint32_t \fBindirect2_addr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 65 of file tfsll\&.c\&.
.SH "Field Documentation"
.PP 
.SS "int32_t direct"
current index of direct block (-1 empty) > 
.PP
Definition at line 66 of file tfsll\&.c\&.
.SS "int32_t indirect1"
current index in indirect1 block (-1 empty) > 
.PP
Definition at line 67 of file tfsll\&.c\&.
.SS "uint32_t indirect1_addr"
current indirect1 block address > 
.PP
Definition at line 69 of file tfsll\&.c\&.
.SS "int32_t indirect2"
current index in indirect2 block (-1 empty) > 
.PP
Definition at line 68 of file tfsll\&.c\&.
.SS "uint32_t indirect2_addr"
current indirect2 block address > 
.PP
Definition at line 70 of file tfsll\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for The Tiny Toy File System from the source code\&.
