.TH "block" 3 "Fri Jan 15 2016" "Version By : V. Fontaine, M.Y. Megrini, N. Scotto Di Perto" "The Tiny Toy File System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
block \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <block\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBbyte\fP \fBdata\fP [\fBD_BLOCK_SIZE\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
A structure to represent blocks 
.PP
Definition at line 24 of file block\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBbyte\fP data[\fBD_BLOCK_SIZE\fP]"
the block contents 
.PP
Definition at line 25 of file block\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for The Tiny Toy File System from the source code\&.
