.TH "dirent" 3 "Fri Jan 15 2016" "Version By : V. Fontaine, M.Y. Megrini, N. Scotto Di Perto" "The Tiny Toy File System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dirent \- Directory entry\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tfsll\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBd_ino\fP"
.br
.ti -1c
.RI "char \fBd_name\fP [\fBTFS_NAME_MAX\fP+1]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Directory entry\&. 

A directory entry contains a file number and a name\&. 
.PP
Definition at line 87 of file tfsll\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t d_ino"
file number 
.PP
Definition at line 88 of file tfsll\&.h\&.
.SS "char d_name[\fBTFS_NAME_MAX\fP+1]"
entry name 
.PP
Definition at line 89 of file tfsll\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for The Tiny Toy File System from the source code\&.
