.TH "disk_ent" 3 "Fri Jan 15 2016" "Version By : V. Fontaine, M.Y. Megrini, N. Scotto Di Perto" "The Tiny Toy File System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
disk_ent \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [\fBD_NAME_MAXLEN\fP+1]"
.br
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "uint32_t \fBsize\fP"
.br
.ti -1c
.RI "uint32_t \fBnpart\fP"
.br
.ti -1c
.RI "uint32_t \fBpart\fP [\fBD_PARTMAX\fP+1]"
.br
.ti -1c
.RI "time_t \fBtime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A structure containing informations about an opened disk 
.PP
Definition at line 21 of file ll\&.c\&.
.SH "Field Documentation"
.PP 
.SS "int fd"
file descriptor 
.PP
Definition at line 24 of file ll\&.c\&.
.SS "char name[\fBD_NAME_MAXLEN\fP+1]"
name of the disk 
.PP
Definition at line 22 of file ll\&.c\&.
.SS "uint32_t npart"
number of partitions 
.PP
Definition at line 26 of file ll\&.c\&.
.SS "uint32_t part[\fBD_PARTMAX\fP+1]"
size of partitions, null at the creation\&. 
.PP
Definition at line 27 of file ll\&.c\&.
.SS "uint32_t size"
size of the disk 
.PP
Definition at line 25 of file ll\&.c\&.
.SS "time_t time"
disk session start time 
.PP
Definition at line 28 of file ll\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for The Tiny Toy File System from the source code\&.
