.TH "File" 3 "Fri Jan 15 2016" "Version By : V. Fontaine, M.Y. Megrini, N. Scotto Di Perto" "The Tiny Toy File System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
File \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tfsll\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBdisk_id\fP \fBid\fP"
.br
.ti -1c
.RI "uint32_t \fBvol_addr\fP"
.br
.ti -1c
.RI "uint32_t \fBinode\fP"
.br
.ti -1c
.RI "sem_t * \fBsem\fP"
.br
.ti -1c
.RI "uint32_t \fBoffset\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBsubtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 99 of file tfsll\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int flags"

.PP
Definition at line 105 of file tfsll\&.h\&.
.SS "\fBdisk_id\fP id"

.PP
Definition at line 100 of file tfsll\&.h\&.
.SS "uint32_t inode"

.PP
Definition at line 102 of file tfsll\&.h\&.
.SS "uint32_t offset"

.PP
Definition at line 104 of file tfsll\&.h\&.
.SS "sem_t* sem"

.PP
Definition at line 103 of file tfsll\&.h\&.
.SS "int subtype"

.PP
Definition at line 107 of file tfsll\&.h\&.
.SS "int type"

.PP
Definition at line 106 of file tfsll\&.h\&.
.SS "uint32_t vol_addr"

.PP
Definition at line 101 of file tfsll\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for The Tiny Toy File System from the source code\&.
