.TH "tfs_description" 3 "Fri Jan 15 2016" "Version By : V. Fontaine, M.Y. Megrini, N. Scotto Di Perto" "The Tiny Toy File System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tfs_description \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBmagic_number\fP"
.br
.ti -1c
.RI "uint32_t \fBblock_size\fP"
.br
.ti -1c
.RI "uint32_t \fBvolume_size\fP"
.br
.ti -1c
.RI "uint32_t \fBfreeb_count\fP"
.br
.ti -1c
.RI "uint32_t \fBfreeb_first\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxfile_count\fP"
.br
.ti -1c
.RI "uint32_t \fBfreefile_count\fP"
.br
.ti -1c
.RI "uint32_t \fBfreefile_first\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 53 of file tfsll\&.c\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t block_size"

.PP
Definition at line 55 of file tfsll\&.c\&.
.SS "uint32_t freeb_count"

.PP
Definition at line 57 of file tfsll\&.c\&.
.SS "uint32_t freeb_first"

.PP
Definition at line 58 of file tfsll\&.c\&.
.SS "uint32_t freefile_count"

.PP
Definition at line 60 of file tfsll\&.c\&.
.SS "uint32_t freefile_first"

.PP
Definition at line 61 of file tfsll\&.c\&.
.SS "uint32_t magic_number"

.PP
Definition at line 54 of file tfsll\&.c\&.
.SS "uint32_t maxfile_count"

.PP
Definition at line 59 of file tfsll\&.c\&.
.SS "uint32_t volume_size"

.PP
Definition at line 56 of file tfsll\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for The Tiny Toy File System from the source code\&.
