.TH "src/tfs_analyze.c" 3 "Fri Jan 15 2016" "Version By : V. Fontaine, M.Y. Megrini, N. Scotto Di Perto" "The Tiny Toy File System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tfs_analyze.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'll\&.h'\fP
.br
\fC#include 'error\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'block\&.h'\fP
.br
\fC#include 'tfs\&.h'\fP
.br
\fC#include <getopt\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMODE_DISK\fP   1 /***< Mode analyze disk */"
.br
.ti -1c
.RI "#define \fBMODE_PART\fP   2 /***< Mode analyze \fBpartition\fP */"
.br
.ti -1c
.RI "#define \fBMODE_LONG\fP   4 /***< Mode analyze long */"
.br
.ti -1c
.RI "#define \fBDEF_NAME\fP   'disk\&.tfs'   /***< default disk name */"
.br
.ti -1c
.RI "#define \fBD_NAME_MAXLEN\fP   79     /***< disk name maximum length */"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBerror\fP \fBtfs_analyze\fP (char *name, int mode, int \fBpartition\fP)"
.br
.RI "\fIAnalyze a disk Print the size of the disk, number of partitions and size of them @param name the name of the disk @param mode the mode (MODE_LONG,MODE_PART,MODE_DISK) @param partition the index of partition @return error\&. \fP"
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define D_NAME_MAXLEN   79     /***< disk name maximum length */"

.PP
Definition at line 20 of file tfs_analyze\&.c\&.
.SS "#define DEF_NAME   'disk\&.tfs'   /***< default disk name */"

.PP
Definition at line 17 of file tfs_analyze\&.c\&.
.SS "#define MODE_DISK   1 /***< Mode analyze disk */"

.PP
Definition at line 12 of file tfs_analyze\&.c\&.
.SS "#define MODE_LONG   4 /***< Mode analyze long */"

.PP
Definition at line 14 of file tfs_analyze\&.c\&.
.SS "#define MODE_PART   2 /***< Mode analyze \fBpartition\fP */"

.PP
Definition at line 13 of file tfs_analyze\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 103 of file tfs_analyze\&.c\&.
.SS "\fBerror\fP tfs_analyze (char * name, int mode, int partition)"

.PP
Analyze a disk Print the size of the disk, number of partitions and size of them @param name the name of the disk @param mode the mode (MODE_LONG,MODE_PART,MODE_DISK) @param partition the index of partition @return error\&. 
.PP
Definition at line 30 of file tfs_analyze\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Tiny Toy File System from the source code\&.
