.TH "src/tfs_ls.c" 3 "Fri Jan 15 2016" "Version By : V. Fontaine, M.Y. Megrini, N. Scotto Di Perto" "The Tiny Toy File System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tfs_ls.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'tfsll\&.h'\fP
.br
\fC#include 'tfs\&.h'\fP
.br
\fC#include 'error\&.h'\fP
.br
\fC#include 'utils\&.h'\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <getopt\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOPT_HELP\fP   'h'"
.br
.ti -1c
.RI "#define \fBOPT_HELP_LONG\fP   'help'"
.br
.ti -1c
.RI "#define \fBOPT_STRING\fP   'h'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBusage\fP (char *argv0)"
.br
.ti -1c
.RI "void \fBhelp\fP (char *argv0)"
.br
.ti -1c
.RI "void \fBls\fP (char *argv0, char *path)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct option \fBoptions\fP [4]"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define OPT_HELP   'h'"

.PP
Definition at line 25 of file tfs_ls\&.c\&.
.SS "#define OPT_HELP_LONG   'help'"

.PP
Definition at line 26 of file tfs_ls\&.c\&.
.SS "#define OPT_STRING   'h'"

.PP
Definition at line 28 of file tfs_ls\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void help (char * argv0)"

.PP
Definition at line 152 of file tfs_ls\&.c\&.
.SS "void ls (char * argv0, char * path)"

.PP
Definition at line 74 of file tfs_ls\&.c\&.
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 46 of file tfs_ls\&.c\&.
.SS "void usage (char * argv0)"

.PP
Definition at line 146 of file tfs_ls\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "struct option options[4]"
\fBInitial value:\fP
.PP
.nf
= {
  { OPT_HELP_LONG, no_argument, 0, OPT_HELP },
  { 0, 0, 0, 0 }
}
.fi
.PP
Definition at line 32 of file tfs_ls\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Tiny Toy File System from the source code\&.
