.TH "src/tfs_partition.c" 3 "Fri Jan 15 2016" "Version By : V. Fontaine, M.Y. Megrini, N. Scotto Di Perto" "The Tiny Toy File System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tfs_partition.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'll\&.h'\fP
.br
\fC#include 'error\&.h'\fP
.br
\fC#include 'block\&.h'\fP
.br
\fC#include 'utils\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <getopt\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <inttypes\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOPTSTRING\fP   'afhs:n:'"
.br
.ti -1c
.RI "#define \fBOPT_SIZE\fP   's'"
.br
.ti -1c
.RI "#define \fBOPT_LONG_SIZE\fP   'size'"
.br
.ti -1c
.RI "#define \fBOPT_NAME\fP   'n'"
.br
.ti -1c
.RI "#define \fBOPT_LONG_NAME\fP   'name'"
.br
.ti -1c
.RI "#define \fBOPT_FORCE\fP   'f'"
.br
.ti -1c
.RI "#define \fBOPT_LONG_FORCE\fP   'force'"
.br
.ti -1c
.RI "#define \fBOPT_HELP\fP   'h'"
.br
.ti -1c
.RI "#define \fBOPT_LONG_HELP\fP   'help'"
.br
.ti -1c
.RI "#define \fBOPT_APPEND\fP   'a'"
.br
.ti -1c
.RI "#define \fBOPT_LONG_APPEND\fP   'append'"
.br
.ti -1c
.RI "#define \fBMOD_SAFE\fP   1"
.br
.ti -1c
.RI "#define \fBMOD_APPEND\fP   2"
.br
.ti -1c
.RI "#define \fBMOD_FORCE\fP   4"
.br
.ti -1c
.RI "#define \fBMOD_HELP\fP   8"
.br
.ti -1c
.RI "#define \fBMOD_DEFAULT\fP   \fBMOD_SAFE\fP"
.br
.ti -1c
.RI "#define \fBYES\fP   1"
.br
.ti -1c
.RI "#define \fBNO\fP   0"
.br
.ti -1c
.RI "#define \fBHELP_OPTION\fP(OPT_LONG,  OPT_SHORT,  DESCRIPTION)   printf('  -%c, --%s\\t %s\\n', OPT_LONG, OPT_SHORT, DESCRIPTION)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBerror\fP \fBpartition\fP (char *name, uint32_t *partsize, int nb_part, long long unsigned totalsize, short mode)"
.br
.ti -1c
.RI "\fBerror\fP \fBpart_append\fP (\fBdisk_id\fP d_id, uint32_t *partsize, int nb_part, long long unsigned totalsize)"
.br
.ti -1c
.RI "\fBerror\fP \fBpart_force\fP (\fBdisk_id\fP d_id, uint32_t *partsize, int nb_part, long long unsigned totalsize)"
.br
.ti -1c
.RI "\fBerror\fP \fBpart_safe\fP (\fBdisk_id\fP d_id, uint32_t *partsize, int nb_part, long long unsigned totalsize)"
.br
.ti -1c
.RI "void \fBusage\fP (char *argv0, FILE *out)"
.br
.RI "\fIPrint a message about usage of the command\&. \fP"
.ti -1c
.RI "void \fBhelp\fP (char *argv0)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.RI "\fIPartitionate the disk\&. Write the partition table of a disk\&. \fP"
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HELP_OPTION(OPT_LONG, OPT_SHORT, DESCRIPTION)   printf('  -%c, --%s\\t %s\\n', OPT_LONG, OPT_SHORT, DESCRIPTION)"

.PP
Definition at line 251 of file tfs_partition\&.c\&.
.SS "#define MOD_APPEND   2"

.PP
Definition at line 24 of file tfs_partition\&.c\&.
.SS "#define MOD_DEFAULT   \fBMOD_SAFE\fP"

.PP
Definition at line 27 of file tfs_partition\&.c\&.
.SS "#define MOD_FORCE   4"

.PP
Definition at line 25 of file tfs_partition\&.c\&.
.SS "#define MOD_HELP   8"

.PP
Definition at line 26 of file tfs_partition\&.c\&.
.SS "#define MOD_SAFE   1"

.PP
Definition at line 23 of file tfs_partition\&.c\&.
.SS "#define NO   0"

.PP
Definition at line 29 of file tfs_partition\&.c\&.
.SS "#define OPT_APPEND   'a'"

.PP
Definition at line 20 of file tfs_partition\&.c\&.
.SS "#define OPT_FORCE   'f'"

.PP
Definition at line 16 of file tfs_partition\&.c\&.
.SS "#define OPT_HELP   'h'"

.PP
Definition at line 18 of file tfs_partition\&.c\&.
.SS "#define OPT_LONG_APPEND   'append'"

.PP
Definition at line 21 of file tfs_partition\&.c\&.
.SS "#define OPT_LONG_FORCE   'force'"

.PP
Definition at line 17 of file tfs_partition\&.c\&.
.SS "#define OPT_LONG_HELP   'help'"

.PP
Definition at line 19 of file tfs_partition\&.c\&.
.SS "#define OPT_LONG_NAME   'name'"

.PP
Definition at line 15 of file tfs_partition\&.c\&.
.SS "#define OPT_LONG_SIZE   'size'"

.PP
Definition at line 13 of file tfs_partition\&.c\&.
.SS "#define OPT_NAME   'n'"

.PP
Definition at line 14 of file tfs_partition\&.c\&.
.SS "#define OPT_SIZE   's'"

.PP
Definition at line 12 of file tfs_partition\&.c\&.
.SS "#define OPTSTRING   'afhs:n:'"

.PP
Definition at line 11 of file tfs_partition\&.c\&.
.SS "#define YES   1"

.PP
Definition at line 28 of file tfs_partition\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void help (char * argv0)"

.PP
Definition at line 253 of file tfs_partition\&.c\&.
.SS "int main (int argc, char * argv[])"

.PP
Partitionate the disk\&. Write the partition table of a disk\&. 
.PP
\fBParameters:\fP
.RS 4
\fIargc\fP 
.br
\fIargv\fP -p size (one ore more) 
.br
\fI\fP 
.RE
.PP

.PP
Definition at line 53 of file tfs_partition\&.c\&.
.SS "\fBerror\fP part_append (\fBdisk_id\fP d_id, uint32_t * partsize, int nb_part, long long unsigned totalsize)"

.PP
Definition at line 176 of file tfs_partition\&.c\&.
.SS "\fBerror\fP part_force (\fBdisk_id\fP d_id, uint32_t * partsize, int nb_part, long long unsigned totalsize)"

.PP
Definition at line 119 of file tfs_partition\&.c\&.
.SS "\fBerror\fP part_safe (\fBdisk_id\fP d_id, uint32_t * partsize, int nb_part, long long unsigned totalsize)"

.PP
Definition at line 144 of file tfs_partition\&.c\&.
.SS "\fBerror\fP partition (char * name, uint32_t * partsize, int nb_part, long long unsigned totalsize, short mode)"

.PP
Definition at line 211 of file tfs_partition\&.c\&.
.SS "void usage (char * argv0, FILE * out)"

.PP
Print a message about usage of the command\&. 
.PP
\fBParameters:\fP
.RS 4
\fIargv0\fP name of the command 
.RE
.PP

.PP
Definition at line 247 of file tfs_partition\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Tiny Toy File System from the source code\&.
