.TH "src/tfs_cat.c" 3 "Fri Jan 15 2016" "Version By : V. Fontaine, M.Y. Megrini, N. Scotto Di Perto" "The Tiny Toy File System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tfs_cat.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <getopt\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'tfs\&.h'\fP
.br
\fC#include 'tfsll\&.h'\fP
.br
\fC#include 'utils\&.h'\fP
.br
\fC#include 'block\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOPT_HELP\fP   'h'"
.br
.ti -1c
.RI "#define \fBOPT_HELP_LONG\fP   'help'"
.br
.ti -1c
.RI "#define \fBOPT_STRING\fP   'h:'"
.br
.ti -1c
.RI "#define \fBPATH_FORMAT\fP   -1"
.br
.ti -1c
.RI "#define \fBPATH_MISSING\fP   -2"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBusage\fP (char *argv0)"
.br
.ti -1c
.RI "void \fBhelp\fP (char *argv0)"
.br
.ti -1c
.RI "\fBerror\fP \fBcat\fP (char *path)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct option \fBoptions\fP [2]"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define OPT_HELP   'h'"

.PP
Definition at line 14 of file tfs_cat\&.c\&.
.SS "#define OPT_HELP_LONG   'help'"

.PP
Definition at line 15 of file tfs_cat\&.c\&.
.SS "#define OPT_STRING   'h:'"

.PP
Definition at line 17 of file tfs_cat\&.c\&.
.SS "#define PATH_FORMAT   -1"

.PP
Definition at line 19 of file tfs_cat\&.c\&.
.SS "#define PATH_MISSING   -2"

.PP
Definition at line 20 of file tfs_cat\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBerror\fP cat (char * path)"

.PP
Definition at line 42 of file tfs_cat\&.c\&.
.SS "void help (char * argv0)"

.PP
Definition at line 33 of file tfs_cat\&.c\&.
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 59 of file tfs_cat\&.c\&.
.SS "void usage (char * argv0)"

.PP
Definition at line 28 of file tfs_cat\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "struct option options[2]"
\fBInitial value:\fP
.PP
.nf
= {
  { OPT_HELP_LONG, no_argument, 0, OPT_HELP },
  { 0, 0, 0, 0 }
}
.fi
.PP
Definition at line 22 of file tfs_cat\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Tiny Toy File System from the source code\&.
