.TH "lib/utils.c" 3 "Fri Jan 15 2016" "Version By : V. Fontaine, M.Y. Megrini, N. Scotto Di Perto" "The Tiny Toy File System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/utils.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ctype\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <inttypes\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTRBADCHAR\fP   (-1)"
.br
.ti -1c
.RI "#define \fBUINT32TOOBIG\fP   (-10)"
.br
.ti -1c
.RI "#define \fBYES\fP   1"
.br
.ti -1c
.RI "#define \fBNO\fP   0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "long long int \fBatou\fP (char *s)"
.br
.ti -1c
.RI "int \fBanswer\fP (char *prompt)"
.br
.RI "\fIThis function waits for an answer from the user\&. \fP"
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NO   0"

.PP
Definition at line 35 of file utils\&.c\&.
.SS "#define STRBADCHAR   (-1)"

.PP
Definition at line 7 of file utils\&.c\&.
.SS "#define UINT32TOOBIG   (-10)"

.PP
Definition at line 8 of file utils\&.c\&.
.SS "#define YES   1"

.PP
Definition at line 34 of file utils\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int answer (char * prompt)"

.PP
This function waits for an answer from the user\&. 
.PP
\fBParameters:\fP
.RS 4
\fIprompt\fP message for the user 
.RE
.PP
\fBReturns:\fP
.RS 4
Returns 0 for [n/N] and 1 for [y/Y]
.RE
.PP
This function displays a prompt message <prompt> and waits for the user's answer and returns it 
.PP
Definition at line 45 of file utils\&.c\&.
.SS "long long int atou (char * s)"
atou cast a string to a long long int destined to to be a uint32_t\&.
.PP
\fBParameters:\fP
.RS 4
\fIthe\fP string to cast 
.RE
.PP
\fBReturns:\fP
.RS 4
a long long int that fit in uint32_t or -1 if the string contains bad characters -10 if the string doesn't fit it uint32_t 
.RE
.PP

.PP
Definition at line 19 of file utils\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Tiny Toy File System from the source code\&.
